### ISSUE TITLE
"Something went wrong" when installing on Z-Way 2.2.2

### ISSUE THREAD

**Issue by alexeyzimarev** [maros/Zway-Presence#2]
When installing the app on Z.Way 2.2.2, I get "something went wrong".

I get one error in the event log:

> 23:12 | Failed to load module because dependency was not instanciated: [DEP]::[MODUL] = BaseModule :: Presence

and then for each installation attempt:

> 23:12 | Cannot instantiate module: Presence: TypeError: undefined is not a function

The "base" module is installed.

**Comment by maros** [comment]
BaseModule must also be instantiated via App > Base Module > Add App (see https://github.com/maros/Zway-BaseModule#installation)

**Comment by alexeyzimarev** [comment]
When I try to instantiate the Base module, it gives the same error on the screen (something went wrong) and no entries in event log.
