### ISSUE TITLE
More Elements

### ISSUE THREAD

**Issue by Eweol** [maros/Zway-Presence#5]
Is there a chance that you implement the posibility to create elements for different smartphones for example so that I don't have the three elements one time but three times for three smartphones?

**Comment by maros** [comment]
Thank you for your feature request. However, could you please elaborate on what you are trying to achieve with this module. Frankly, I'm not entirely sure what this module has to do with smartphones? Also this module is a Singleton - only one instance of the Presence module is supported - not sure how/why to configure multiple instances

**Comment by Eweol** [comment]
Sry for my late response.
I saw that is set to singleton in module.json but I worked first with Ping-Presence/now with my own Modul FritzBoxPresence to control your Presence Module.
Now I have the problem that my wife and my child also have and need a presence state to control everything right. 
So I need 3 instances of Presence-Modul.
Thats why I asked you to make it to a multi-instance module where I can set names for different Presence-Module's.

**Comment by maros** [comment]
Presence module can only have one instance and many other modules rely on this fact. Hence you probably need to find another solution - eg. having one virtual device per mobile device to track the individual presence state and one condition switch to OR the individual states into one presence state.
